// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVKrs6yYn0HqYf8nS5dCO7_U9_lJ3L2_Q',
    appId: '1:46262626629:web:5a24c6420f994dc27a362c',
    messagingSenderId: '46262626629',
    projectId: 'perudo-489b2',
    authDomain: 'perudo-489b2.firebaseapp.com',
    databaseURL: 'https://perudo-489b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'perudo-489b2.appspot.com',
    measurementId: 'G-E7N0DZMH1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBReK4-e0BZRNiR9obftUrwRkr0byZ10jQ',
    appId: '1:46262626629:android:04c2fea0657993d67a362c',
    messagingSenderId: '46262626629',
    projectId: 'perudo-489b2',
    databaseURL: 'https://perudo-489b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'perudo-489b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZlf93nOfosvY3Bg3uJ1MjJbO5er1y-qA',
    appId: '1:46262626629:ios:84bb734cc6abd5247a362c',
    messagingSenderId: '46262626629',
    projectId: 'perudo-489b2',
    databaseURL: 'https://perudo-489b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'perudo-489b2.appspot.com',
    iosBundleId: 'com.example.perudo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZlf93nOfosvY3Bg3uJ1MjJbO5er1y-qA',
    appId: '1:46262626629:ios:84bb734cc6abd5247a362c',
    messagingSenderId: '46262626629',
    projectId: 'perudo-489b2',
    databaseURL: 'https://perudo-489b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'perudo-489b2.appspot.com',
    iosBundleId: 'com.example.perudo',
  );
}
