// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY8RLw1EGIbJxWqUHjSaHiJaZ6NaCgVqc',
    appId: '1:531167939442:web:6f946aa4f39f7ab5a26beb',
    messagingSenderId: '531167939442',
    projectId: 'perudo-flutter',
    authDomain: 'perudo-flutter.firebaseapp.com',
    storageBucket: 'perudo-flutter.appspot.com',
    measurementId: 'G-JXW0YLRPBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKjX7OaMHG7_M1VzYny9LqRHSQnjZGkEk',
    appId: '1:531167939442:android:7b910fa1b55d3a90a26beb',
    messagingSenderId: '531167939442',
    projectId: 'perudo-flutter',
    storageBucket: 'perudo-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkLyUCz4C53edvuqiROWH7u3wqIsTahwQ',
    appId: '1:531167939442:ios:26209cd54e563c2da26beb',
    messagingSenderId: '531167939442',
    projectId: 'perudo-flutter',
    storageBucket: 'perudo-flutter.appspot.com',
    iosClientId: '531167939442-2ddkh7iekeoicc10hiva36148s265cc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.perudo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkLyUCz4C53edvuqiROWH7u3wqIsTahwQ',
    appId: '1:531167939442:ios:26209cd54e563c2da26beb',
    messagingSenderId: '531167939442',
    projectId: 'perudo-flutter',
    storageBucket: 'perudo-flutter.appspot.com',
    iosClientId: '531167939442-2ddkh7iekeoicc10hiva36148s265cc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.perudo',
  );
}
